feat(docker-compose.yml): containerized mongoDB and redis for Kaze
sdslabs/gasper pull request #196
Opened 2020-04-08 19:43 UTC by aryaman-titan

@alphadose Plz check the **docker-compose.yml** file and tell me if it's okay to continue with this for further using it in Kaze.

2020-04-08 20:56 UTC, supra08 commented
Well, as discussed over slack, we are not going with this approach (using docker-compose or dockerfiles). You might want to look how mongoDB service is actually setup in gasper and how you can apply the same for setting up gasper's mongoDB. Refer this:
https://sdslabs.slack.com/archives/CCAFCAWT0/p1586298950144200

2020-04-08 20:59 UTC, aryaman-titan commented
> Well, as discussed over slack, we are not going with this approach (using docker-compose or dockerfiles). You might want to look how mongoDB service is actually setup in gasper and how you can apply the same for setting up gasper's mongoDB. Refer this:
> https://sdslabs.slack.com/archives/CCAFCAWT0/p1586298950144200

Okay cool! I'll just look upon the setting up of the service! :+1:

2020-04-10 05:04 UTC, karan0299 commented
Squash the last two commits

2020-04-10 17:18 UTC, karan0299 requested changes
I have left some comments, I will test this branch by tomorrow and will let you know and any further changes are required

2020-04-10 17:18 UTC, karan0299 commented on lib/database/handler.go
> +			fmt.Println(port)
Remove this

2020-04-10 17:18 UTC, karan0299 commented on lib/database/handler.go
> +			storedir := filepath.Join(storepath, "mongodb-storage")
```suggestion
			storedir := filepath.Join(storepath, "gasper-mongodb-storage")
```

2020-04-10 17:18 UTC, karan0299 commented on lib/database/handler.go
> +			storedir := filepath.Join(storepath, "redis-storage")
```suggestion
			storedir := filepath.Join(storepath, "gasper-redis-storage")
```

2020-04-10 17:18 UTC, karan0299 commented on lib/database/handler.go
> +			fmt.Println(port)
Remove print statement

2020-04-14 03:38 UTC, alphadose commented on config.sample.toml
> +redis = "redis:latest"
replace this with `redis:6.0-rc3-alpine3.11`

2020-04-15 08:39 UTC, alphadose requested changes

2020-04-15 08:39 UTC, alphadose commented on config.sample.toml
> +
Remove this unnecessary line

2020-04-15 08:39 UTC, alphadose commented on config.sample.toml
> -port = 3000
why delete this ?

2020-04-15 08:39 UTC, alphadose commented on config.sample.toml
> +container_port = 6380  # Port on which the Redis server container will run
add environment variables for the user and password of both of them. See how it is done below for mongodb. Find the equivalent for redis

2020-04-15 08:39 UTC, alphadose commented on config.sample.toml
>  url = "mongodb://localhost:27017"
change it to the port on which your mongodb container is running

2020-04-15 08:39 UTC, alphadose commented on config.sample.toml
>  ###########################
change the port here as well to the redis container you created

2020-04-16 04:16 UTC, alphadose requested changes

2020-04-16 04:16 UTC, alphadose commented on config.sample.toml
> +url = "mongodb://localhost:27019"
If you have populated these values
```
MONGO_INITDB_ROOT_USERNAME = "YOUR_ROOT_NAME"   # Root user of MongoDB server inside the container
MONGO_INITDB_ROOT_PASSWORD = "YOUR_ROOT_PASSWORD"   # Root password of MongoDB server inside the container
```

then the connection URL will be `mongodb://YOUR_ROOT_NAME:YOUR_ROOT_PASSWORD@localhost:27019`

2020-04-19 11:46 UTC, alphadose requested changes

2020-04-19 11:46 UTC, alphadose commented on config.sample.toml
The password for redis container should be declared here and used when creating the container

2020-04-19 11:46 UTC, alphadose commented on lib/database/mongo.go
> +	mongoGasperPort     = configs.ServiceConfig.Kaze.MongoDB.ContainerPort
Are these 3 needed ?

2020-04-21 21:25 UTC, supra08 approved these changes

2020-04-23 05:42 UTC, alphadose requested changes

2020-04-23 05:42 UTC, alphadose commented on lib/database/handler.go
> +		workdir:     "/app",
workdir should be `/var/lib/mysql`

`/app` will be the workdir for the new image not this one

2020-04-24 13:19 UTC, alphadose approved these changes

2020-04-24 13:20 UTC, merged