chore(config.sample.toml): update images pulled from dockerhub
sdslabs/gasper pull request #234
Opened 2022-01-14 16:21 UTC by yashre-bh

2022-02-03 18:11 UTC, mhk19 requested changes

2022-02-03 18:11 UTC, mhk19 commented on lib/api/application.go
> +		return types.NewResErr(500, "git init unsuccessful", err)
```suggestion
		setup <- types.NewResErr(500, "git init unsuccessful", err)
		return
```
This should be like this

2022-02-03 18:11 UTC, mhk19 commented on lib/api/application.go
> +		return types.NewResErr(500, "setting remote unsuccessful", err)
same as above

2022-02-03 18:11 UTC, mhk19 commented on lib/api/application.go
> +		return types.NewResErr(500, "pulling contents unsuccessful", err)
same as above

2022-02-03 18:11 UTC, mhk19 commented on services/appmaker/controller.go
> +				return nil, fmt.Errorf("cannot deploy more than %d app instances in %d hours", rateCount, timeInterval)
why this change

2022-02-03 18:11 UTC, mhk19 commented on services/appmaker/controller.go
> +			return nil, fmt.Errorf("cannot deploy more than %d app instances", maxCount)
why this change

2022-02-03 18:11 UTC, mhk19 commented on services/appmaker/controller.go
> +		return nil, fmt.Errorf("language `%s` is not supported", language)
why this change

2022-02-03 18:11 UTC, mhk19 commented on services/appmaker/controller.go
> +	_, err = docker.ExecProcess(app.ContainerID, pullChanges)
are we sure that the container will be up?

2022-02-03 18:17 UTC, yashre-bh commented on services/appmaker/controller.go
> +				return nil, fmt.Errorf("cannot deploy more than %d app instances in %d hours", rateCount, timeInterval)
error strings should not be capitalized (ST1005) go-staticcheck: the linter for go suggested this change

2022-02-03 18:17 UTC, yashre-bh commented on services/appmaker/controller.go
> +			return nil, fmt.Errorf("cannot deploy more than %d app instances", maxCount)
error strings should not be capitalized (ST1005) go-staticcheck: the linter for go suggested this change

2022-02-03 18:18 UTC, yashre-bh commented on services/appmaker/controller.go
> +		return nil, fmt.Errorf("language `%s` is not supported", language)
error strings should not be capitalized (ST1005) go-staticcheck: the linter for go suggested this change

2022-02-03 18:38 UTC, yashre-bh commented on lib/api/application.go
> +		return types.NewResErr(500, "git init unsuccessful", err)
[here](https://github.com/sdslabs/gasper/blob/44c8d3adcd6bb84698a20e3d3fbe388a54402669/lib/api/application.go#L121)

This is the function definition (as on the develop branch).
`setup channel` was not passed as a parameter in `SetupApplication()` function, I did not alter this. Will I still have to make this change?

2022-03-16 10:25 UTC, mhk19 approved these changes

2022-03-16 10:28 UTC, merged